name: E2E on Chrome
on:
  push:
    branches: [dev]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        ref: ${{ github.head_ref }}

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'

      - name: Push to master
        if: ${{ success() }} # This step only runs if the "Cypress run" step succeeds
        run: |
          git checkout master
          git merge ${{ github.head_ref }}
          git push origin master
