name: E2E on Chrome
on:
  push:
    branches: [master]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'
      
      - name: Deploy to Vercel
          if: ${{ success() }} # runs only if previous step (cypress tests) are successful
            run: npx vercel --prod
            env: 
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
