name: E2E on Chrome
on:
  push:
    branches: [dev]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          project: ./
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: 'http://localhost:3000'

      - name: Merge changes
        if: ${{ success() }} # This step only runs if the "Install dependencies" step succeeds
        run: git merge origin/master

      - name: Push changes
        run: git push
